name: totor
version: 1.0.0
summary: Like hallociné but worse
description: find, rate and review movies

confinement: strict
base: core18
grade: stable

slots:
  dbus-totor: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.matteogassend.totor # adjust accordingly to your app name and

apps:
  totor:
    command: totor
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
      - network
    slots:
      - dbus-totor
parts:
  totor:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
